// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk4sgJjwi9JYv8cAh3hm_ol0SEigT-z94',
    appId: '1:694030655377:web:c9ca8e888c17f452420430',
    messagingSenderId: '694030655377',
    projectId: 'deliverymanager-ffaf1',
    authDomain: 'deliverymanager-ffaf1.firebaseapp.com',
    storageBucket: 'deliverymanager-ffaf1.firebasestorage.app',
    measurementId: 'G-3JSQW1ZJY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQWhSKITj5Yl8-Wf4Y8AYqD_idgc6bMDg',
    appId: '1:694030655377:android:c1a0a66abb025a7e420430',
    messagingSenderId: '694030655377',
    projectId: 'deliverymanager-ffaf1',
    storageBucket: 'deliverymanager-ffaf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9izSC46C7yuXdaTK_FHC1_oF7nPNUg6c',
    appId: '1:694030655377:ios:39724b1d5719573d420430',
    messagingSenderId: '694030655377',
    projectId: 'deliverymanager-ffaf1',
    storageBucket: 'deliverymanager-ffaf1.firebasestorage.app',
    iosBundleId: 'com.example.codDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9izSC46C7yuXdaTK_FHC1_oF7nPNUg6c',
    appId: '1:694030655377:ios:39724b1d5719573d420430',
    messagingSenderId: '694030655377',
    projectId: 'deliverymanager-ffaf1',
    storageBucket: 'deliverymanager-ffaf1.firebasestorage.app',
    iosBundleId: 'com.example.codDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk4sgJjwi9JYv8cAh3hm_ol0SEigT-z94',
    appId: '1:694030655377:web:2f2c2d3c3ad38d1d420430',
    messagingSenderId: '694030655377',
    projectId: 'deliverymanager-ffaf1',
    authDomain: 'deliverymanager-ffaf1.firebaseapp.com',
    storageBucket: 'deliverymanager-ffaf1.firebasestorage.app',
    measurementId: 'G-1XMGPQGH9K',
  );
}
